### ISSUE TITLE
How to configure runtime options?

### ISSUE THREAD

**Issue by frameworker2019** [David-Haim/concurrencpp#100]
I cannot find an example how to configure the [runtime options](https://github.com/David-Haim/concurrencpp/blob/0c612ae3de006405b66cccdba7d62168442c95ff/source/runtime/runtime.cpp#L57)
Please provide a short example.

```
concurrencpp::runtime runtime;

runtime.max_background_threads = 8 // for example
```

**Comment by David-Haim** [comment]
Hi there
In order to use the runtime options class, you instantiate it on the stack, change whatever parameters you need, then you pass it to the constructor of `runtime`.

For example, let's say that I suspect that 10 cpu threads and 20 io threads will give the best performance for my app, then I can write 

```cpp
concurrencpp::runtime_options opts;
opts.max_cpu_threads = 10;
opts.max_background_threads = 20;

concurrencpp::runtime runtime(opts);
```

you are then guaranteed that `runtime.thread_pool_executor()` has 10 workers and `runtime.background_executor()` has 20 workers.
