### ISSUE TITLE
Crashed in coroutine by access the captured variable in lambda

### ISSUE THREAD

**Issue by austringer** [David-Haim/concurrencpp#113]
Compiler: vs2022
I made this test example
```c++
int i = 0;

concurrencpp::result<int> getValue(std::shared_ptr<concurrencpp::executor> executor)
{
    assert(executor != nullptr);
    co_await resume_on(executor); // <- If comment this line, it works fine.
    std::cout << executor->name << std::endl;

    co_return i++;
}

int main()
{
    concurrencpp::runtime runtime;
    auto executor = runtime.thread_executor();

    executor->post([executor]() noexcept -> concurrencpp::null_result // <- same crash if change the post() to submit() without return
        {
            int i = 0;
            while (i++ < 3)
            {
                auto value = co_await getValue(executor); // <- failed to copy the captured shared_ptr at second time.
                std::cout << value << std::endl;
            }
            co_return;
        });

    std::this_thread::sleep_for(std::chrono::seconds(1));
    return 0;
}
```
expected to output
```
concurrencpp::thread_executor
0
concurrencpp::thread_executor
1
concurrencpp::thread_executor
2
```
but it crashed before the second call to getValue().

If I change the lambda to
```c++
    executor->post([executor]() noexcept -> concurrencpp::null_result
        {
            auto ex = executor; // <- make a local variable
            int i = 0;
            while (i++ < 3)
            {
                auto value = co_await getValue(ex); // <- use the local variable
                std::cout << value << std::endl;
            }
            co_return;
        });
```
or sync waiting the result
```c++
    auto r = executor->submit([executor]() noexcept -> concurrencpp::null_result // <- get a result
        {
            int i = 0;
            while (i++ < 3)
            {
                auto value = co_await getValue(executor);
                std::cout << value << std::endl;
            }
            co_return;
        });
    r.wait(); // <- wait the result;
```
it works properly as expected.

I encountered a crash when testing async_condition_variable and found that it seems to be caused by resume_on(). Not sure if it's due to an early called destructor.

**Comment by David-Haim** [comment]
Hi there!
This is a known problem with capturing lambdas that are also coroutines, and has nothing to do with concurrencpp.
please read the very informative post by [Raymond Chen](https://devblogs.microsoft.com/oldnewthing/20211103-00/?p=105870).

In a nutshell, that fact the coroutine is also a lambda does not mean that the lambda capture is preserved until the coroutine finishes. lambdas are compiled to anonymous structs, where captures are member-variables. the coroutine compiles to an `operator ()` which captures `this` implicitly, allowing it to access the captures. the problem is that when you launch this coroutine-operator(), it goes back to the caller the moment you `co_await` inside it, and the destructor of the anonymous class is called.

If you run the example in debug mode, you would see the next assert being triggered:

```
concurrencpp::thread_executor
0
Assertion failed: executor != nullptr, file C:\Users\David\Desktop\example\concurrencpp\sandbox\main.cpp, line 8
```

In order to avoid such problem, use a parallel coroutines, save the capture locally, or sync the result as you did.
I advise to avoid capturing-lamdas coroutines at all cost, parallel coroutines are the way to go:

```
null_result parallel_coro(executor_tag, std::shared_ptr<thread_executor> ex){
            int i = 0;
            while (i++ < 3)
            {
                auto value = co_await getValue(ex); // <- use the local variable
                std::cout << value << std::endl;
            }
}

parallel_coro({}, executor);
```
