### ISSUE TITLE
CI/CD options

### ISSUE THREAD

**Issue by nightlark** [David-Haim/concurrencpp#14]
This is adding on to the comments from this reddit thread: https://www.reddit.com/r/cpp/comments/j04one/concurrencpp_v006_modern_concurrency_for_c/g6oijwk/

For multiple processors, using a beefier CircleCI instance as other comments have mentioned could be a good option, though I don't think they have native ARM builders. The upside is they support the main OSes, Windows, Linux, and macOS.

One option I've been using on some projects for ARM builds is [Drone Cloud](https://cloud.drone.io/); they offer native ARM and x86 builders (only Linux), and it seems they give access to a lot of cores on the build machines.

The roadmap for GitHub Actions includes GitHub hosted runners with different machines types (extra CPU, RAM, etc) in the future. Not sure what the timeline for that is, but the integration between GitHub and GitHub Actions is hard to beat.

**Comment by David-Haim** [comment]
Hi
Thanks for the info.

The way it looks right now, there is no holistic solution, as this library needs the matrix of [win,linux,macOS] x [arm, intel] + at least 4 logical cores. currently it doesn't seem like there's a CI/CD system that provides all the above.

I decided to go with Circle ci because they at least provide all OSs + up to 16 cores. no ARM there, but better than what Github actions/Gitlab/appveyor/Travis provide. The downside is that CircleCI isn't really made for C++ CI/CD, you pretty much have to install everything from scratch.

Also, I saw that Drone Cloud is docker based. Personally, I despise Docker. the product itself is decent but developing images and pipelines (at least for me) has always been pain. 

I made a working pipleline for linux in one of the branches, currently working on developing CI/CD for Windows.
Feel free to fork the project and add any CI/CD pipeline you feel appropriate, I'm not attached to any system.

**Comment by nightlark** [comment]
I'll check out the Linux CircleCI branch you made later for setting up ARM CI builds. The way I've used Drone Cloud I just use one of the default base image for the jobs and then treat it like any other yaml-based CI configuration file rather than developing custom Docker images.
