### ISSUE TITLE
Maturity and roadmap?

### ISSUE THREAD

**Issue by patlecat** [David-Haim/concurrencpp#68]
This lib looks very interesting and covers really about anything we need when using coroutines. How mature and well tested is it for productive systems? Do you have some banchmarks maybe? And what is the plan and next steps for it?

**Comment by David-Haim** [comment]
Hello, and thank you for your interest in concurrencpp.

As for maturity - My answer will be split into 2 - compiler maturity and the library maturity:

MSVC is pretty stable and I trust their implementation to be almost bug free, they have worked continously on their coroutine support since 2015.
Clang is slowley getting there, personally I haven't seen any problems with clang-12 coroutine support, but I would keep an eye open for generated assembly bugs that it may generate.
I would suspect Applclang though, as it seems that C++20 is actually not a high priority for it, and the coroutine support seems a bit buggy.
GCC is currently not supported at all. GCC-11 came with a very buggy coroutine support. maybe it will change with GCC-12.
GCC support will be added when GCC's coroutine support becomes mature enough.
In any case, If you're using any coroutine-support library, my advice is to test your code thoroughly with unit tests and load tests, TSAN should always be used (but even then, watch out for false positives!).

As for the library maturity: The library is heavily tested and the coverage is absolute. 
Data races are eliminated by utilizing load tests with Clang's thread-sanitizer.
For production cases, I would wait for the next version (0.1.5) which hopefully will be released in the next weeks. 
the next version contains some nice optimizations and will provide `async_lock` capability which is an important component for every coroutine-based code.

As for benchmarks, I do internally benchmark the library against previous versions of it.
However, there aren't a lot of coroutine libraries out there that are both mature and follow the concurrencpp vision for concurrent code  (eager and lazy are both equal in importance, executors as a basis of execution, a sane, safe, intuitive library for asynchronous code).
cppcoro is both abandoned, and anyway never provided any eager-execution capabilities. 
folly, as far as I understand, seems close to concurrencpp in nature, but I haven't really tried to benchmark it against my library.
libunifx doesn't allow eager execution and anyway, I refuse to acknowledge this ugly, complicated DSL-callback hell as a valid concurrency library. 

As for future steps - fortunatly, concurrencpp is getting at its final stages. then next versions will add `async_lock` and `async_condition_variable` and by doing so the end developers will have a complete, rich toolkid for writing their asynchronous, coroutine based code.
Hopefully then I'll get to work on the next big library - concurrencpp-io, which should be used on top of concurrencpp, 
and will provide asynchronous IO and networking.

Feel free to ask any other questions. 
David.
