### ISSUE TITLE
Support clang with other standard libraries

### ISSUE THREAD

**Issue by ohanar** [David-Haim/concurrencpp#86]
I've successfully built with clang and have ran the test suite (including TSAN where applicable) on the following platforms:
- Ubuntu 22.04, libstdc++ 11
- Ubuntu 22.04, libstdc++ 12
- Windows, MSVC 14.33.31629*

It seems reasonable to support an OS's defacto stl implementation when possible.

* There is one failure on Windows when using clang with Microsoft's STL arising from the handling of exceptions. Seems like clang doesn't handle things correctly sometimes when exceptions are caught by value. The test suite passes when [this line](https://github.com/David-Haim/concurrencpp/blob/master/test/include/utils/test_ready_lazy_result.h#L63) is changed to catch by const reference rather than value.

**Comment by David-Haim** [comment]
Hi there!
Thanks for the check.
For the record, I don't think I mandated any standard library flavor, just the compiler and OS.
As long as the standard library adheres to the standard specification, it should be alright. 
It's the assembly code generation that usually makes the problems, this is why I require some minimal compiler version for each compiler.

**Comment by ohanar** [comment]
[These lines](https://github.com/David-Haim/concurrencpp/blob/master/cmake/coroutineOptions.cmake#L8-L9) means that anyone who wants to use clang with something other than libc++ needs to modify the cmake. It would be better if this was a cmake option that could be enabled or disabled at configure time.

**Comment by chausner** [comment]
I think the reason why currently ` -stdlib=libc++` is hardcoded for Clang is because Clang 13 and earlier only supported coroutines via libc++ (via header `<experimental/coroutine>`). Coroutines were not implemented yet in the corresponding version of libstdc++. With Clang 14 and later, both libstdc++ and libc++ support coroutines (via header `<coroutine>`).

I agree that it's better to not hardcode the stdlib and let the user choose instead whether to use libstdc++ or libc++. It would then be up to the user to specify libc++ if using Clang 13 or earlier.

**Comment by David-Haim** [comment]
OK I'm convinced, what do you guys think the best solution for this? 
Simply removing std specification from the cmake all together will fail the compilation
